name: POST IMAGE TO ACR

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  post-image-to-acr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ai200-app:ci .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: |
          az acr login --name vamsiai200acr

      - name: Tag Docker image
        run: |
          docker tag ai200-app:ci vamsiai200acr.azurecr.io/ai200-app:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push vamsiai200acr.azurecr.io/ai200-app:${{ github.sha }}